version: '3.5'

services:
  hero_engineer_mongo:
    image: mongo
    volumes:
      - ~/hero_engineer_data/mongo/data:/data/db
    container_name: hero_engineer_mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: M!]mBSVe.9P{uk7XprbnR.dRk)b7v"7C
      MONGO_INITDB_DATABASE: heroEngineer
    networks:
      - hero_engineer_network
  hero_engineer_backend:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ~/hero_engineer_data/uploads:/uploads
      - ~/hero_engineer_data/reports:/reports
    container_name: hero_engineer_backend_container
    depends_on:
      - hero_engineer_mongo
    networks:
      - hero_engineer_network

networks:
  hero_engineer_network:
    name: hero_engineer_network
    driver: bridge
